# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: create env file
      run: |
        touch .env
        echo TEST_TOKEN=${{ secrets.TEST_TOKEN }} >> .env
        echo TEST_PROJECT_ID=${{ secrets.TEST_PROJECT_ID }} >> .env
        echo TEST_DOMAIN=${{ secrets.TEST_DOMAIN }} >> .env
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: npm install -g zapier-platform-cli
    - run: zapier test
